CXX = g++
CFLAGS = -I  ../include
CFLAGS1 = -I ../include -c
all: asm

asm: main.o AsmFunctions.o input.o
	$(CXX) $(CFLAGS) obj/main.o obj/AsmFunctions.o obj/input.o -o asm
main.o: src/main.cpp 
	$(CXX) $(CFLAGS1) src/main.cpp -o obj/main.o
AsmFunctions.o: src/AsmFunctions.cpp
	$(CXX) $(CFLAGS1) src/AsmFunctions.cpp -o obj/AsmFunctions.o
input.o: src/input.cpp
	$(CXX) $(CFLAGS1) src/input.cpp -o obj/input.o
clean:
	rm -rf *.o proc
